---
title: "Portfolio CM"
knit: (function(input_file, encoding) {
  out_dir <- 'portfolio';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output:  
  flexdashboard::flex_dashboard:
    storyboard: true
---

Introduction {data-icon="fa-thin fa-folder-music"}
=================

I have chosen to compare spotify's decade playlists (All out 60's, All out 70's, All out 80's, All out 90's) to find out what is typical for each decade. More specifically, I would expect to find a difference in aspects as danceability and energy. Of course there are also certain artists and genres that are decade defining. At first glance it is noticable that some artist appear on playlists for more than one decade. For example, ABBA appears in the 'All out 70's' playlist as well as the 'All out 60's' playlist, this shows that certain genres were popular throughout more than one decade. THe playlists appear to be fairly representative. They contain multiple songs by artists of which the genre is often associated with that decade but they also have a fair amount of 'one hit wonders', showing that the decades are not only defined by certain artists but also by music style.

Typical/atypical songs:

80's The 80's are often known for reverb (voice manipulation) and electronic/synthesizer sound as well as being very upbeat and 'danceable'. A typical song for this decade would be 'Don't you want me' by The Human League. A song that feels atypical, though it was very popular would be 'Pump up the jam' by Technotronic as it feels very electronic.

90's The 90's had a variety of pop, rap and alternative/grunge music. So we can expect to find a wider variety of genres. It is difficult to find a typical song due to the different genres, however an atypical songs to me seems 'Mambo No.5' by Lou Bega, which I find difficult to place into a certain genre.


Plots
=================

Discussion
=================